# Generated by Django 3.1.7 on 2021-03-25 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireChargement',
            fields=[
                ('formulaire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.formulaire')),
                ('vehicule', models.CharField(max_length=255, verbose_name='Numéro de véhicule')),
                ('bon_de_livraison', models.CharField(max_length=255, verbose_name='Numéro bon de livraison')),
                ('sacs_sortis', models.IntegerField(verbose_name='Nombre de sacs à la fin du chargement')),
                ('bonus', models.BooleanField(default=False, verbose_name='Chargement avec bonus ou pas')),
            ],
            bases=('home.formulaire',),
        ),
    ]
