# Generated by Django 3.1.7 on 2021-03-21 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
                ('controleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MachineEnsacheuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=4, verbose_name='Code Machine Ensacheuse')),
            ],
        ),
        migrations.CreateModel(
            name='ParametresMicrobiologiques',
            fields=[
                ('formulaire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suiviqualite.formulaire')),
                ('microorganismes_22', models.IntegerField(default=0, verbose_name='MICROORGANISMES REVIVIFIABLES 22°C')),
                ('microorganismes_36', models.IntegerField(default=0, verbose_name='MICROORGANISMES REVIVIFIABLES 36°C')),
                ('microorganismes_44', models.IntegerField(default=0, verbose_name='MICROORGANISMES REVIVIFIABLES 44°C')),
                ('coliformes_totaux', models.IntegerField(default=0, verbose_name='COLIFORMES TOTAUX')),
                ('coliformes_fecaux', models.IntegerField(default=0, verbose_name='COLIFORMES FECAUX')),
                ('e_coli', models.IntegerField(blank=True, default=0, null=True, verbose_name='E.COLI')),
                ('pseudomonas', models.CharField(choices=[('A', 'Absence'), ('P', 'Présence')], default='A', max_length=1, verbose_name='pseudomonas')),
            ],
            bases=('suiviqualite.formulaire',),
        ),
        migrations.CreateModel(
            name='ParametresPhysicoChimiques',
            fields=[
                ('formulaire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suiviqualite.formulaire')),
                ('chlore_libre', models.FloatField(verbose_name='Chlore Libre')),
                ('chlore_total', models.FloatField(verbose_name='Chlore Total')),
                ('turbidite', models.FloatField(verbose_name='Turbidité')),
                ('ph', models.FloatField(verbose_name='PH')),
                ('durete', models.IntegerField(verbose_name='Dureté')),
                ('nitrate', models.FloatField(blank=True, null=True, verbose_name='Nitrate')),
            ],
            bases=('suiviqualite.formulaire',),
        ),
        migrations.CreateModel(
            name='ParametresMetrologiques',
            fields=[
                ('formulaire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='suiviqualite.formulaire')),
                ('poids', models.IntegerField()),
                ('quart', models.CharField(choices=[('Q1', '1er Quart'), ('Q2', '2e Quart'), ('Q3', '3e Quart')], max_length=2, verbose_name='Quart de Production')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suiviqualite.machineensacheuse')),
            ],
            bases=('suiviqualite.formulaire',),
        ),
    ]
