# Generated by Django 3.1.7 on 2021-03-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireProduction',
            fields=[
                ('formulaire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.formulaire')),
                ('quart_de_production', models.CharField(choices=[('Q1', '1er Quart'), ('Q2', '2e Quart'), ('Q3', '3e Quart')], max_length=2, verbose_name='Quart de Production')),
                ('sacs_produits', models.IntegerField(verbose_name='Nombre de sacs produits')),
            ],
            bases=('home.formulaire',),
        ),
    ]
