# Generated by Django 3.1.7 on 2021-03-24 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('suiviproduction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireCasse',
            fields=[
                ('formulaire_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.formulaire')),
                ('casses_recues', models.IntegerField(default=0, verbose_name='Casses reçues')),
                ('casses_traitees', models.IntegerField(default=0, verbose_name='Casses traitées')),
                ('dotation_commerciaux', models.IntegerField(default=0, verbose_name='Dotation commerciaux')),
                ('dotation_personnel', models.IntegerField(default=0, verbose_name='Dotation au personnel (Frigo interne)')),
                ('retour_commerciaux', models.IntegerField(default=0, verbose_name='Retour commerciaux')),
                ('casse_reelle', models.IntegerField(default=0, verbose_name='Casse réelle')),
            ],
            bases=('home.formulaire',),
        ),
    ]
